### ISSUE TITLE
Is it still possible to use oath2 for facebook and twitter?

### ISSUE THREAD

**Issue by firstchair** [weld-co/telescope-theme-weld#63]
Hé, great telescope theme but is it still possible to use oath2?

**Comment by jamiewilson** [comment]
Yeah, I believe it's actually just hidden with CSS. The oauth was still kinda buggy when I first created this, so I had to just hide it for the time being.

**Comment by firstchair** [comment]
Thanks for the great reply, do you also know why the grid function not is working anymore?

**Comment by jamiewilson** [comment]
Yeah. Sorry. That was introduced well after I created the theme and because we don't need it for our purposes, I haven't implemented it. When I update to the latest telescope release, I'll likely design that as well. 

Also, here's the CSS related to Oauth: https://github.com/weld-co/telescope-theme-weld/blob/master/client/scss/modules/_accounts.scss

**Comment by firstchair** [comment]
Wow, great response! Thanks

**Comment by firstchair** [comment]
@jamiewilson I think the css of http://welderwire.meteor.com/ and the theme on github are different, right?

**Comment by jamiewilson** [comment]
Oops. sorry, i let that get behind. Should be up to date in a few minutes.
